# For more information, see:
# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available
resolver: lts-12.24

packages:
  - '.'

extra-deps:
  - github: mpickering/slack-api
    commit: ab91568180b18daabe9e1be8ea82f5cb361f2465
  - aeson-1.4.2.0
  - hedis-0.10.10
  - wreq-0.5.2.1

# Extra directories used by stack for building
extra-include-dirs: [/usr/local/opt/openssl/include]
extra-lib-dirs: [/usr/local/opt/openssl/lib]
